### ISSUE TITLE
Bug: time not working correctly

### ISSUE THREAD

**Issue by zetaab** [http-wasm/http-wasm-guest-tinygo#33]
guest code https://github.com/zetaab/traefik-wasm-demo

I am running it as Traefik plugin https://github.com/traefik/traefik/pull/10189

Full instructions available in https://github.com/zetaab/traefik-wasm-demo/blob/main/readme.md#use-with-traefik

After wasm plugin is compiled and Traefik is running. When I am doing http request, it will response time.Now() to traefik logs (that is coming from rows https://github.com/zetaab/traefik-wasm-demo/blob/main/header.go#L40-L41):

```
2023-10-26T17:05:09Z DBG pkg/plugins/logger.go:31 > time is 2022-01-01 00:00:00.001 +0000 UTC m=+1640995200.001000001 entryPointName=web middlewareName=localWasm@file middlewareType=wasm routerName=customer1@file
``` 

I also tried api.ConsoleLogger from Traefik side, but still the issue is same (so the issue is not in logger). I have now tried to run this with linux amd64 and darwin arm64. In both it will display wrong timestamp always. I have no idea is this bug report in correct github repository or not.

**Comment by zetaab** [comment]
Times are working fine if compile time package with tinygo

```
package main

import (
	"fmt"
	"time"
)

func main() {
	t := time.Now()
	fmt.Println("Hello from Go! The time is", t.String())
}
```

```
% tinygo build -o foo ./foo.go && ./foo
Hello from Go! The time is 2023-10-26 20:19:54.585265 +0300 EEST m=+40790.762145751
```

minimal example with wasi:

```
package main

import (
  "fmt"
  "time"
)

func main() {
  t := time.Now()
  fmt.Println("Hello world" + t.String())
}
```

```
% tinygo build -target=wasi -scheduler=none -o main.wasm main.go
% wasmtime main.wasm                                           
Hello world2023-10-26 17:30:23.610329 +0000 UTC m=+1698341423.610329001
```

So that works as well

**Comment by zetaab** [comment]
I added minimal server to https://github.com/zetaab/traefik-wasm-demo/tree/main/server and README.md contains also instructions how to reproduce the issue.

**Comment by jcchavezs** [comment]
Cc @mathetake

**Comment by zetaab** [comment]
@jcchavezs this is bug in wazero. I will move this discussion there

**Comment by zetaab** [comment]
this is not bug in this repository, so I will close this
